repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  # Pyrefly type checking - temporarily disabled due to config issues
  # - repo: local
  #   hooks:
  #     - id: pyrefly
  #       name: pyrefly type check
  #       entry: pyrefly check
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
